### ISSUE TITLE
name suggests to display but this exists on logic

### ISSUE THREAD

**Issue by AlexKap23** [Drifta7/tic-tac-toe#2]
https://github.com/Drifta7/tic-tac-toe/blob/7b87b5ec941065f5dfe293d421aacfe5c7ba1b71/Logic.cs#L11-L25
Since this is displaying the grid, it has an interaction with the user. That tells me that this is a UI method and not a logical one. It would be logical if the grid was just being generated, but since you display that, then this method is a UI one.

And this is an issue for almost all your Logical methods since all of them are displaying something.

**Comment by Drifta7** [comment]
resolved and moved to UI methods
