### ISSUE TITLE
Where's the grid?

### ISSUE THREAD

**Issue by AlexKap23** [Drifta7/tic-tac-toe#3]
https://github.com/Drifta7/tic-tac-toe/blob/7b87b5ec941065f5dfe293d421aacfe5c7ba1b71/Program.cs#L16

This method is generating a grid internally and displays it. But the grid exists only on the context of this method and not on the whole program. How about considering the grid creation into the Program.cs and then passing that as a param inside every method that needs it? For example pass it as a param in the method that it will generate the random numbers for it and then pass it as a param in the method that it's going to display it etc

**Comment by Drifta7** [comment]
fixed and resolved as a stand-alone public static string[,] ticTacToeGrid = new string[GameConstants.NUMBER_OF_ROWS,GameConstants.NUMBER_OF_COLUMNS];
