### ISSUE TITLE
How about simplifying that method a bit?

### ISSUE THREAD

**Issue by AlexKap23** [Drifta7/tic-tac-toe#4]
https://github.com/Drifta7/tic-tac-toe/blob/7b87b5ec941065f5dfe293d421aacfe5c7ba1b71/UiMethods.cs#L52-L82

1. In general methods should do only one thing at a time. And this is because it's easier to maintain them, easier to debug them and isolate problems that can occur and of course easier to extend them. This method is getting an input, validates it and then "places" it on the grid. I see at least 2 methods here, one for getting the input and validating it and another for placing that on the grid. 
2. this method is not placing player's input on the grid, since there's no grid available here and it's also a void, so it's not returning anything back to be used to place the input on the grid. So either an adjustment is needed or the name should be changed in my opinion.

**Comment by Drifta7** [comment]
MapPostionToGrid and PlacingPlayerEntryOnGrid() have both been separated and are now functioning on their own and are now working
